name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.2
          profile: minimal
          
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install solc
        run: (hash svm 2>/dev/null || cargo install svm-rs) && svm install 0.8.20 && svm use 0.8.20 && solc --version

      - name: Run test (mv lookups)
        run: cargo test --workspace --all-features --all-targets -- --nocapture
      - name: Run test (non-mv lookups)
        run: cargo test --workspace --all-targets -- --nocapture
      - name: Run separate example
        run: cargo run --package halo2_solidity_verifier --example separately --all-features -- --nocapture

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings
